//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCrawData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOAT_DONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOAT_DONG()
        {
            this.CHUONG_TRINH = new HashSet<CHUONG_TRINH>();
            this.QUY_DINH = new HashSet<QUY_DINH>();
            this.THAMGIA_HOATDONG = new HashSet<THAMGIA_HOATDONG>();
        }
    
        public int MaHoatDong { get; set; }
        public string TenHoatDong { get; set; }
        public string MaTieuChi { get; set; }
        public Nullable<bool> MaLoaiHoatDong { get; set; }
        public string Cap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUONG_TRINH> CHUONG_TRINH { get; set; }
        public virtual LOAI_HOAT_DONG LOAI_HOAT_DONG { get; set; }
        public virtual TIEU_CHI TIEU_CHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUY_DINH> QUY_DINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THAMGIA_HOATDONG> THAMGIA_HOATDONG { get; set; }
    }
}
