//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCrawData
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUA_THEO_TIEUCHI
    {
        public string Mssv { get; set; }
        public string MaTieuChi { get; set; }
        public string DanhGia { get; set; }
        public Nullable<int> TienDoDat { get; set; }
    
        public virtual TIEU_CHI TIEU_CHI { get; set; }
        public virtual SINH_VIEN SINH_VIEN { get; set; }
    }
}
