//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCrawData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ĐT_QL_SV5TOTEntities : DbContext
    {
        public ĐT_QL_SV5TOTEntities()
            : base("name=ĐT_QL_SV5TOTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUONG_TRINH> CHUONG_TRINH { get; set; }
        public virtual DbSet<DON_VI> DON_VI { get; set; }
        public virtual DbSet<HOAT_DONG> HOAT_DONG { get; set; }
        public virtual DbSet<KETQUA_THEO_TIEUCHI> KETQUA_THEO_TIEUCHI { get; set; }
        public virtual DbSet<LOAI_DIEM> LOAI_DIEM { get; set; }
        public virtual DbSet<LOAI_HOAT_DONG> LOAI_HOAT_DONG { get; set; }
        public virtual DbSet<QUY_DINH> QUY_DINH { get; set; }
        public virtual DbSet<SINH_VIEN> SINH_VIEN { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THAMGIA_CHUONGTRINH> THAMGIA_CHUONGTRINH { get; set; }
        public virtual DbSet<THAMGIA_HOATDONG> THAMGIA_HOATDONG { get; set; }
        public virtual DbSet<THOIGIAN_XET> THOIGIAN_XET { get; set; }
        public virtual DbSet<TIEU_CHI> TIEU_CHI { get; set; }
    }
}
