//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCrawData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINH_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINH_VIEN()
        {
            this.KETQUA_THEO_TIEUCHI = new HashSet<KETQUA_THEO_TIEUCHI>();
            this.THAMGIA_CHUONGTRINH = new HashSet<THAMGIA_CHUONGTRINH>();
            this.THAMGIA_HOATDONG = new HashSet<THAMGIA_HOATDONG>();
            this.THOIGIAN_XET = new HashSet<THOIGIAN_XET>();
        }
    
        public string Mssv { get; set; }
        public string HoTen { get; set; }
        public string Lop { get; set; }
        public string Khoa { get; set; }
        public string DonVi { get; set; }
        public string Email { get; set; }
    
        public virtual DON_VI DON_VI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUA_THEO_TIEUCHI> KETQUA_THEO_TIEUCHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THAMGIA_CHUONGTRINH> THAMGIA_CHUONGTRINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THAMGIA_HOATDONG> THAMGIA_HOATDONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THOIGIAN_XET> THOIGIAN_XET { get; set; }
    }
}
